### PR TITLE
Optional heap and permgen args for java VM

### PR DESCRIPTION
**Pull request by ghost**
Allow optional `$jenkins_max_heap_size` and `$jenkins_max_perm_size` vars to control heap and permgen sizes in Jenkins Java VM via `java` command line args.

Usage:

```
$jenkins_max_heap_size = "6G"
$jenkins_max_perm_size = "512M"
include jenkins
```

Both variables are optional. Arguments to `java` are only added if the corresponding variable is set.

### CODE REVIEW

**Comment by bilke** [comment]
Thanks for your contribution! I tried a few things but I also was not able to set the variables (I am a puppet noob in fact...).

**Comment by ghost** [comment]
Noob also. I'll see if I can get help on IRC. Also reading puppet tutorial and have one more idea to try. If I figure it out, I'll update and re-open this PR.

**Comment by ghost** [comment]
Figured it out. Updated the PR.

**Comment by bilke** [comment]
@toolbear Where do you define the variables? For me they seem to be out of scope in `config.pp` (with a value of `undef`) no matter where I define them (I tried in my personal config under `modules/people/manifests` and also in `manifests/site.pp`).

**Comment by ghost** [comment]
Sorry for late reply. I noticed that it was merged, but missed your comment asking about it.

For me, defining them in a `node` block in `manifests/site.pp` works:

```
node 'vendacious.local' {
  # core modules, needed for most things
  include dnsmasq
  …

  # jenkins
  $jenkins_max_heap_size = "6G"
  $jenkins_max_perm_size = "512M"
  include java
  include jenkins

  …
}
```

The values had to be assigned prior to `include jenkins`. I didn't try setting them in `modules/people/manifests`. My (limited) understanding of variable scoping in puppet is that these have to be defined in the block, or containing block, of the `include jenkins` for it to work.

I'm not particularly pleased how this works, but that it works at all is a step forward, I feel.

**Comment by bilke** [comment]
Yes I also assigned the values prior to `include jenkins`.

Thanks, defining it in a `node` block works for me too!

**Pull request merged**
